"use client";

import React, { useEffect, useState, useCallback } from "react";
import { AlertCircle, Loader2 } from "lucide-react";
import { getMonthlyAnalytics } from "@/lib/sheets";
import { MetricCard, MetricComparison } from "./metric-card";
import { supabase } from "@/lib/supabase";
import { startOfMonth, endOfMonth, subMonths } from "date-fns";
import { PastMonthsDialog } from "./past-months-dialog";
import { HistoricalSnapshotView } from "./historical-snapshot-view";

export function AnalyticsView() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<any>(null);
  const [totalHours, setTotalHours] = useState<number>(0);
  const [prevSnapshot, setPrevSnapshot] = useState<any>(null);
  
  const [selectedHistorical, setSelectedHistorical] = useState<any>(null);

  const fetchLiveAndPreviousData = useCallback(async () => {
    setLoading(true);
    try {
      const now = new Date();
      const prevDate = subMonths(now, 1);
      const prevMonthKey = `${prevDate.getFullYear()}-${(prevDate.getMonth() + 1).toString().padStart(2, '0')}`;

      // 1. Fetch live current month & check for prev snapshot
      const [sheetsResult, sessionsResult, prevSnapshotResult] = await Promise.all([
        getMonthlyAnalytics(),
        fetchCurrentMonthHours(now),
        supabase.from("analytics_monthly_snapshots").select("*").eq("month", prevMonthKey).maybeSingle()
      ]);

      if (sheetsResult.error) {
        setError(sheetsResult.error);
      } else {
        setData(sheetsResult.data);
      }

      setTotalHours(sessionsResult);
      
      // 2. Safely grab the snapshot generated by the cron job (if any)
      setPrevSnapshot(prevSnapshotResult?.data || null);
    } catch (err: any) {
      setError(err.message || "Failed to load analytics.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchLiveAndPreviousData();
  }, [fetchLiveAndPreviousData]);

  const fetchCurrentMonthHours = async (date: Date): Promise<number> => {
    const start = startOfMonth(date).toISOString();
    const end = endOfMonth(date).toISOString();

    const { data: sessions, error } = await supabase
      .from("work_sessions")
      .select("duration")
      .gte("started_at", start)
      .lte("started_at", end)
      .not("ended_at", "is", null);

    if (error) return 0;
    if (!sessions) return 0;
    const totalSeconds = sessions.reduce((acc, curr) => acc + (curr.duration || 0), 0);
    return totalSeconds / 3600;
  };

  if (selectedHistorical) {
    return <HistoricalSnapshotView snapshot={selectedHistorical} onBack={() => setSelectedHistorical(null)} />;
  }

  const formatCurrency = (val: number) => {
    return val.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const formatPercent = (val: number) => {
    return val.toFixed(1);
  };

  const safeData = data || {
    revenue: 0,
    cogs: 0,
    grossProfit: 0,
    grossMargin: 0,
    itemsSold: 0,
    avgSalePrice: 0,
    avgProfitPerItem: 0,
    monthLabel: "Current Month"
  };

  const profitPerHour = totalHours > 0 ? safeData.grossProfit / totalHours : 0;

  const getComparison = (current: number, previous: number | undefined): MetricComparison | null => {
    if (previous === undefined || previous === null || previous === 0) return null;
    const diff = current - previous;
    const percentage = (diff / previous) * 100;
    return {
      percentage: Math.abs(percentage),
      isPositive: diff >= 0,
      label: `vs ${prevSnapshot.month_label}`
    };
  };

  return (
    <div className="flex flex-col gap-6 animate-in fade-in zoom-in-95 duration-500 relative">
      <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-border pb-4 gap-4">
        <h2 className="text-sm uppercase tracking-[0.2em] text-muted-foreground flex items-center gap-2">
          {safeData.monthLabel} Live
          {loading && <Loader2 className="w-3 h-3 animate-spin text-muted-foreground/50" />}
        </h2>
        
        <PastMonthsDialog onOpenSnapshot={setSelectedHistorical} />
      </div>

      {error && (
        <div className="flex items-center gap-2 text-red-400/80 bg-red-500/10 rounded-lg px-4 py-3 border border-red-500/20 text-xs">
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className={`grid grid-cols-2 md:grid-cols-4 gap-4 transition-opacity duration-300 ${loading ? "opacity-50" : "opacity-100"}`}>
        <MetricCard 
          title="Revenue" 
          value={formatCurrency(safeData.revenue)} 
          prefix="£"
          comparison={prevSnapshot ? getComparison(safeData.revenue, prevSnapshot.revenue) : null}
        />
        <MetricCard 
          title="Gross Profit" 
          value={formatCurrency(safeData.grossProfit)} 
          prefix="£" 
          comparison={prevSnapshot ? getComparison(safeData.grossProfit, prevSnapshot.gross_profit) : null}
        />
        <MetricCard 
          title="COGS" 
          value={formatCurrency(safeData.cogs)} 
          prefix="£" 
          comparison={prevSnapshot ? getComparison(safeData.cogs, prevSnapshot.cogs) : null}
        />
        <MetricCard 
          title="Gross Margin" 
          value={formatPercent(safeData.grossMargin)} 
          suffix="%" 
          comparison={prevSnapshot ? getComparison(safeData.grossMargin, prevSnapshot.gross_margin) : null}
        />
        
        <MetricCard 
          title="Items Sold" 
          value={safeData.itemsSold} 
          comparison={prevSnapshot ? getComparison(safeData.itemsSold, prevSnapshot.items_sold) : null}
        />
        <MetricCard 
          title="Avg Sale Price" 
          value={formatCurrency(safeData.avgSalePrice)} 
          prefix="£" 
          comparison={prevSnapshot ? getComparison(safeData.avgSalePrice, prevSnapshot.average_sale_price) : null}
        />
        <MetricCard 
          title="Avg Profit/Item" 
          value={formatCurrency(safeData.avgProfitPerItem)} 
          prefix="£" 
          comparison={prevSnapshot ? getComparison(safeData.avgProfitPerItem, prevSnapshot.average_profit_per_item) : null}
        />
        <MetricCard 
          title="Profit / Hour" 
          value={formatCurrency(profitPerHour)} 
          prefix="£" 
          comparison={prevSnapshot ? getComparison(profitPerHour, prevSnapshot.profit_per_hour) : null}
        />
      </div>

      <div className="mt-12 flex justify-center border border-dashed border-border rounded-lg py-8 text-center bg-card/20 text-muted-foreground/50">
        <p className="text-[10px] uppercase tracking-widest">(The rest will be updated in the next phase)</p>
      </div>
    </div>
  );
}
